name = "tomasantonelli-landingpage"
license = "MIT"
description = "Very basic theme for a portfolio/landing page"
homepage = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Tomás Antonelli"
  homepage = "https://tomas-antonelli.xyz"
